### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "luchooo",
  "email": "luis@gmail.com",
  "password": "12345678",
  "avatarUrl": "https://nobita.me/data/resource_icons/0/86.jpg"
}
